#pragma once

#define CUBE_VOXEL_TYPE_BEGIN 0
#define CUBE_VOXEL_TYPE_END 6

#define CUBE_VOXEL_FACE_TYPE_FRONT 0
#define CUBE_VOXEL_FACE_TYPE_BACK 1
#define CUBE_VOXEL_FACE_TYPE_TOP 2
#define CUBE_VOXEL_FACE_TYPE_BOTTOM 3
#define CUBE_VOXEL_FACE_TYPE_RIGHT 4
#define CUBE_VOXEL_FACE_TYPE_LEFT 5